echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "saurav tcs devops"
echo "RE2675S"
echo "change in script1"
echo "saurav maalik gaddar hai"
